---
title: "la2"
output:
  word_document: default
  html_document: default
date: "2023-05-22"
---

```{r setup, include=FALSE}
eda2 <- read.csv("C:/Users/Harip/Downloads/Life Expectancy Data.csv")
View(eda2)
data(eda2)
```

```{r}
```


```{r}
str(eda2)
```

```{r}
summary(eda2)
```

```{r}
plot(eda2$Measles, eda2$BMI)
```

```         
```

```{r}

```

```{r}
library(ggplot2)

ggplot(eda2, aes(x = Measles, y = BMI)) +
  geom_point()
```

```{r}
plot(eda2$Life.expectancy, eda2$polo, type = "l")
```

```{r}
BOD
```

```{r}
barplot(table(eda2$Adult.Mortality))
```
```{r}
```


```{r}
```

```{r}
hist(eda2$Life.expectancy)

# Specify approximate number of bins with breaks

```

```{r}
hist(eda2$Adult.Mortality, breaks = 10)
```

```{r}
plot(eda2$Hepatitis.B, eda2$BMI)
```

```{r}
library(ggplot2)
ggplot(eda2, aes(x = Hepatitis.B, y = BMI)) +
  geom_boxplot()
```

```{r}
curve(x^3 - 5*x, from = -4, to = 4)
```

```{r}
# Plot a user-defined function
myfun <- function(xvar) {
  1 / (1 + exp(-xvar + 10))
}
curve(myfun(x), from = 0, to = 20)
# Add a line:
curve(1 - myfun(x), add = TRUE, col = "red")
```

```{r}
library(ggplot2)
# This sets the x range from 0 to 20
ggplot(data.frame(x = c(0, 20)), aes(x = x)) +
  stat_function(fun = myfun, geom = "line")
```

```{r}
library(gcookbook)  # Load gcookbook for the pg_mean data set
ggplot(eda2, aes(x = Year, y = infant.deaths)) +
  geom_col()
```
```{r}


```
```{r}
```


```{r}
plot(eda2$BMI, eda2$Alcohol)
```
```{r}
library(ggplot2)
ggplot(eda2, aes(x = BMI, y = Alcohol)) +
  geom_boxplot()
```



```{r}
ggplot(eda2, aes(x = interaction(Year, Country), y = BMI)) +
  geom_col() +
  geom_text(aes(label = BMI), vjust = -0.2)
```
```{r}
```


```{r}
ggplot(eda2, aes(x = Year, y = BMI, fill = Alcohol)) +
  geom_col(position = "dodge")
```

```{r}
ggplot(eda2, aes(x = BMI, y = Country)) +
  geom_point()
```
```{r}
ggplot(eda2, aes(x = BMI, y = Hepatitis.B)) +
  geom_point()
```
```{r}
ggplot(eda2, aes(x = BMI, y = reorder(Country, BMI))) +
  geom_point(size = 3) +  # Use a larger dot
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(colour = "grey60", linetype = "dashed")
  )
```
```{r}
ggplot(eda2, aes(x = reorder(Country,BMI), y = BMI)) +
  geom_point(size = 3) +  # Use a larger dot
  theme_bw() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.x = element_line(colour = "grey60", linetype = "dashed"),
    axis.text.x = element_text(angle = 60, hjust = 1)
  )
```

```{r}
hw_p <- ggplot(eda2, aes(x = Alcohol, y = Hepatitis.B))

hw_p +
  geom_violin()
```
```{r}
hw_p +
  geom_violin() +
  geom_boxplot(width = .1, fill = "black", outlier.colour = NA) +
  stat_summary(fun.y = median, geom = "point", fill = "white", shape = 21, size = 2.5)
```
```{r}
hw_p +
  geom_violin(trim = FALSE)
```
```{r}
# More smoothing
hw_p +
  geom_violin(adjust = 2)

# Less smoothing
hw_p +
  geom_violin(adjust = .5)
```
```{r}
ggplot(eda2, aes(x =Schooling, y = Country, fill = GDP)) +
  geom_area()
```
```{r}
ggplot(eda2, aes(x = Year, y = Country, fill = Alcohol)) +
  geom_col() +
  guides(fill = guide_legend(reverse = TRUE))
```
```{r}
ggplot(eda2, aes(x = Year, y = Life.expectancy)) +
  geom_area()
```

```{r}
ggplot(eda2, aes(x = Year, y = Adult.Mortality)) +
  geom_area(fill = "blue", alpha = .2) +
  geom_line()
```
```{r}
ggplot(eda2, aes(x = Year, y = Population)) +
  geom_ribbon(aes(ymin = Population - 2, ymax = Population + 2), alpha = 0.2) +
  geom_line()
```
```{r}
# With a dotted line for upper and lower bounds
ggplot(eda2, aes(x = Year, y = BMI)) +
  geom_line(aes(y = BMI - 3), colour = "grey50", linetype = "dotted") +
  geom_line(aes(y = BMI + 3), colour = "grey50", linetype = "dotted") +
  geom_line()
```
```{r}
ggplot(eda2, aes(x=Life.expectancy)) +
  geom_freqpoly()
```
```{r}
ggplot(eda2, aes(x = Life.expectancy)) +
  geom_freqpoly(binwidth = 4)
```
```{r}
ggplot(eda2, aes(x =Polio)) +
  geom_density()
```

```{r}
ggplot(eda2, aes(x = Polio)) +
  geom_line(stat = "density") +
  geom_line(stat = "density", adjust = .25, colour = "red") +
  geom_line(stat = "density", adjust = 2, colour = "blue")
```

